SEL24 = SELECT * \
          FROM CUSTOMER C \
         WHERE C.LOGIN = ? \
           AND C.PASSWORD = SHA2(?, 256)
           
INS25 = INSERT INTO PURCHASE \
          (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_COUNT, \
          CUSTOMER_NAME, CUSTOMER_ADDRESS, INS_DATETIME, UPD_DATETIME) \
        VALUES \
          (?, ?, ?, ?, ?, ?, NOW(), NOW())


SEL14 = SELECT * \
          FROM PRODUCT

SEL15 = SELECT * \
          FROM PRODUCT \
         WHERE NAME LIKE ?

INS14 = INSERT INTO PRODUCT \
          (NAME, PRICE) \
        VALUES \
          (?, ?)

SEL16 = SELECT COUNT(P.ID) COUNT \
          FROM PRODUCT P \
         WHERE P.NAME = ? 

SEL17 = SELECT P.ID, \
               P.NAME, \
               P.PRICE \
          FROM PRODUCT P \
         WHERE P.PRICE <= ? 
         
SEL18 = SELECT P.ID    ID,    \
               P.NAME  NAME,  \
               P.PRICE PRICE \
          FROM PRODUCT P
          
SEL19 = SELECT P.ID    ID, \
               P.NAME  NAME, \
               P.PRICE PRICE \
          FROM PRODUCT P \
         WHERE P.NAME LIKE ?
         
SEL20 = SELECT P.ID    ID, \
               P.NAME  NAME, \
               P.PRICE PRICE \
          FROM PRODUCT P \
         WHERE P.NAME = ?
         
EXT01 = SELECT EXISTS (SELECT 1 \
                         FROM PRODUCT P \
                        WHERE P.NAME = ? \
                      ) EXTFLG
